-- RAW.CHANNELS — One row per YouTube channel
-- Populated via MERGE in snowflake_loader.py (idempotent upsert)

CREATE OR REPLACE TABLE PODCASTIQ.RAW.CHANNELS (
    CHANNEL_ID      VARCHAR(30)     NOT NULL,
    CHANNEL_NAME    VARCHAR(100)    NOT NULL,
    GENRE           VARCHAR(50)     NOT NULL,
    YOUTUBE_URL     VARCHAR(300),
    CREATED_AT      TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CHANNELS PRIMARY KEY (CHANNEL_ID)
);
